steps:
- name: 'node:10-alpine'
  entrypoint: "npm"
  args: ['ci']
- name: 'node:10-alpine'
  entrypoint: "npm"
  args: ['run', 'build']
- name: 'node:10-alpine'
  entrypoint: "npm"
  args: ['t']
  env:
    - 'CI=true'
    - 'FIRESTORE_EMULATOR_HOST=localhost:8081'
- name: 'node:10-alpine'
  entrypoint: "npm"
  args: ['run', 'deploy']